package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"my_gql_server/graph/model"
)

// CreateBook is the resolver for the CreateBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.BookInput) (*model.Book, error) {
	book, err := r.BookRepository.CreateBook(&input)
	bookCreated := &model.Book{
		Author:    book.Author,
		Publisher: book.Publisher,
		Title:     book.Title,
		ID:        book.ID,
	}
	if err != nil {
		return nil, err
	}
	return bookCreated, nil
}

// DeleteBook is the resolver for the DeleteBook field.
func (r *mutationResolver) DeleteBook(ctx context.Context, id int) (string, error) {
	err := r.BookRepository.DeleteBook(id)
	if err != nil {
		return "", err
	}
	successMessage := "successfully deleted"
	return successMessage, nil
}

// UpdateBook is the resolver for the UpdateBook field.
func (r *mutationResolver) UpdateBook(ctx context.Context, id int, input model.BookInput) (string, error) {
	err := r.BookRepository.UpdateBook(&input, id)
	if err != nil {
		return "nil", err
	}
	successMessage := "successfully updated"

	return successMessage, nil
}

// CreatePan is the resolver for the CreatePan field.
func (r *mutationResolver) CreatePan(ctx context.Context, input model.PanInput) (*model.Pan, error) {
	pan, err := r.PanRepository.CreatePan(&input)
	panCreated := &model.Pan{
		CreatedAt: pan.CreatedAt.String(),
		Name:      pan.Name,
		ID:        pan.ID,
	}
	if err != nil {
		return nil, err
	}
	return panCreated, nil
}

// GetAllBooks is the resolver for the GetAllBooks field.
func (r *queryResolver) GetAllBooks(ctx context.Context) ([]*model.Book, error) {
	books, err := r.BookRepository.GetAllBooks()
	if err != nil {
		return nil, err
	}
	return books, nil
}

// GetOneBook is the resolver for the GetOneBook field.
func (r *queryResolver) GetOneBook(ctx context.Context, id int) (*model.Book, error) {
	book, err := r.BookRepository.GetOneBook(id)
	selectedBook := &model.Book{
		ID:        book.ID,
		Author:    book.Author,
		Publisher: book.Publisher,
		Title:     book.Title,
	}
	if err != nil {
		return nil, err
	}
	return selectedBook, nil
}

// GetAllPans is the resolver for the GetAllPans field.
func (r *queryResolver) GetAllPans(ctx context.Context) ([]*model.Pan, error) {
	pans, err := r.PanRepository.GetAllPans()
	if err != nil {
		return nil, err
	}
	return pans, nil
}

// GetOnePan is the resolver for the GetOnePan field.
func (r *queryResolver) GetOnePan(ctx context.Context, id string) (*model.Pan, error) {
	pan, err := r.PanRepository.GetOnePan(id)
	selectedPan := &model.Pan{
		ID:        pan.ID,
		Name:      pan.Name,
		CreatedAt: pan.CreatedAt.String(),
	}
	if err != nil {
		return nil, err
	}
	return selectedPan, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
